apiVersion: 1

datasources:
  - name: EcoGrid MySQL
    uid: ecogrid_mysql
    type: mysql
    access: proxy
    url: mysql:3306
    database: $MYSQL_DATABASE
    user: $MYSQL_USER
    isDefault: true
    editable: true
    jsonData:
      maxOpenConns: 10
      maxIdleConns: 2
      connMaxLifetime: 14400
    secureJsonData:
      password: $MYSQL_PASSWORD
